# Generated by Django 4.0.4 on 2023-04-08 15:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_rename_text_comment_message_comment_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comm_post',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='comm_user',
        ),
    ]
