# Generated by Django 4.2 on 2023-04-11 10:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('news', '0005_remove_comment_comm_post_remove_comment_comm_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='comm_post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='news.post'),
        ),
        migrations.AddField(
            model_name='comment',
            name='comm_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
