# Generated by Django 4.0.4 on 2023-04-18 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_comment_comm_post_comment_comm_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageMain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
