# Generated by Django 4.0.4 on 2023-02-12 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='ContactForm',
        ),
    ]
