# Generated by Django 4.0.4 on 2023-02-16 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_contactform_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='name',
            field=models.CharField(max_length=50, verbose_name='имя'),
        ),
        migrations.AlterField(
            model_name='contactform',
            name='review',
            field=models.TextField(verbose_name='сщщбщение'),
        ),
    ]
