# Generated by Django 4.0.4 on 2023-05-15 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0005_rename_name_contactform_firstname_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contactform',
            options={'verbose_name': 'Контактная форма', 'verbose_name_plural': 'Контактные формы'},
        ),
        migrations.AlterField(
            model_name='contactform',
            name='lastname',
            field=models.CharField(max_length=50, verbose_name='фамилия'),
        ),
    ]
